FROM mcr.microsoft.com/dotnet/runtime:6.0-bullseye-slim AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:6.0-bullseye-slim AS build
WORKDIR /src
COPY ["NoAudioBot/NoAudioBot.csproj", "NoAudioBot/NoAudioBot.csproj"]
RUN dotnet restore "NoAudioBot/NoAudioBot.csproj"
COPY . .
WORKDIR "/src/NoAudioBot"
RUN dotnet build "NoAudioBot.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "NoAudioBot.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "NoAudioBot.dll"]
