
version: "3"
services:
  bot:
    build:
      context: .
      dockerfile: ./NoAudioBot/dockerfile
    
    volumes:
      - "./token.txt:/app/token.txt"
      - "./templates/english.html:/app/decline-message.html"