name: Publish Docker Images

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: [ "master" ]
    
  workflow_dispatch:
    inputs:
      tags:
        description: 'Run Publish'  
        
env:
  REGISTRY: ghcr.io
  BOT_IMAGE_NAME: noaudiobot


jobs:
  build-and-push-bot:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: docker build . --file NoAudioBot/dockerfile --tag $BOT_IMAGE_NAME

      - name: Tag image
        run: docker tag $BOT_IMAGE_NAME ghcr.io/${{ github.actor }}/$BOT_IMAGE_NAME:latest

      - name: Push client image
        run: docker push ghcr.io/${{ github.actor }}/$BOT_IMAGE_NAME:latest